---
title: "Take-home Labs"
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE, echo=FALSE, results='hide'}
# List of all required packages across labs
required_packages <- c(
  "tidyverse",     # Used throughout for data manipulation and plotting
  "lubridate",     # Lab 8 - date/time handling
  "viridis",       # Lab 7 - color scales
  "purrr",         # Lab 9 - iteration and mapping
  "ggplot2",       # Used throughout for plotting (part of tidyverse but sometimes loaded separately)
  "dplyr",         # Used throughout for data manipulation (part of tidyverse but sometimes loaded separately)
  "readr"          # Used throughout for data import (part of tidyverse but sometimes loaded separately)
)

# Check which packages need to be installed
new_packages <- required_packages[!(required_packages %in% installed.packages()[,"Package"])]

# Install missing packages
if(length(new_packages)) {
  install.packages(new_packages)
}

# Load all required packages
invisible(lapply(required_packages, library, character.only = TRUE))
```

Labs are designed to reinforce the code/lessons covered that week and provide you a chance to practice working with R. Labs are to be completed in your local project (on your computer) and uploaded to Canvas by the beginning of class (1pm) the following Thursday. That said, these due dates are largely suggestive as a way to help you prioritize and stay caught up as a group -- if you need, or want, more time, take it. At the end of the quarter, we will simply look over the tasks you have completed in concert with the reflection you submit.


<br>

## Labs {.tabset .tabset-fade .tabset-pills}

### <small>Lab Week 1</small> {#lab-week-1}

This lab will help you get oriented with R, RStudio, and your first programming concepts. The goal is to practice the fundamentals covered in the the introduction to R and RStudio lecture.

<a href="labs/lab_week_01.qmd" download>Download Lab 1 (.qmd)</a>


### <small>Lab Week 2</small> {#lab-week-2}

In this lab we are going to practice subsetting and manipulating vectors.

<a href="labs/lab_week_02.qmd" download>Download Lab 2 (.qmd)</a>


### <small>Lab Week 3</small> {#lab-week-3}

Lab this week will be playing with the `surveys` data we worked on in class.

<a href="labs/lab_week_03.qmd" download>Download Lab 3 (.qmd)</a>


### <small>Lab Week 4</small> {#lab-week-4}

This week the lab will review data manipulation in the tidyverse.

<a href="labs/lab_week_04.qmd" download>Download Lab 4 (.qmd)</a>


### <small>Lab Week 5</small> {#lab-week-5}

This week's questions will have us practicing pivots and conditional statements.

<a href="labs/lab_week_05.qmd" download>Download Lab 5 (.qmd)</a>


### <small>Lab Week 7</small> {#lab-week-7}

For our week seven lab, we are going to be practicing the skills we learned with ggplot during class. You will be happy to know that we are going to be using a brand new data set called `gapminder`.

<a href="labs/lab_week_07.qmd" download>Download Lab 7 (.qmd)</a>


### <small>Lab Week 8</small> {#lab-week-8}

Let's look at some real data from Mauna Loa to try to format and plot.

<a href="labs/lab_week_08.qmd" download>Download Lab 8 (.qmd)</a>


### <small>Lab Week 9</small> {#lab-week-9}

In this assignment, you'll use the iteration skills we built in the course to apply functions to an entire dataset.

<a href="labs/lab_week_09.qmd" download>Download Lab 9 (.qmd)</a>

