---
title: "Course Outline"
---

<br>

## Course Schedule

| Week | Tuesday | Thursday | Labs |
|---------------|------------------|--------------------------|---------------|
| **Week 1 (9/22-24)** | Setup help: Weds, 12pm-2pm, CEPB Lab, Wickson 2120 | Course intro<br>[Intro to R & RStudio](lesson_wk01_intro_r_rstudio.html)<br>[(submit videos)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714931)<br>[(submit in-class)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714934) | [Lab 1](https://ucd-rdavis.github.io/R-DAVIS/labs.html#lab-week-1)<br>[(submit lab 1)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714943) |
| **Week 2 (9/29-10/1)** | Workshop | [Project Management & How R Thinks About Data](lesson_wk02_project_management_and_data.html)<br>[(submit videos)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714930)<br>[(submit in-class)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714935) | [Lab 2](https://ucd-rdavis.github.io/R-DAVIS/labs.html#lab-week-2)<br>[(submit lab 2)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714944) |
| **Week 3 (10/6-8)** | Workshop | [Spreadsheet Best Practices & Data Import](lesson_wk03_spreadsheets_and_data_import.html)<br>[(submit videos)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714929)<br>[(submit in-class)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714936) | [Lab 3](https://ucd-rdavis.github.io/R-DAVIS/labs.html#lab-week-3)<br>[(submit lab 3)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714945) |
| **Week 4 (10/13-15)** | Workshop | [Data Manipulation Pt1](lesson_wk04_data_manipulation_pt1.html)<br>[(submit videos)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714928)<br>[(submit in-class)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714937) | [Lab 4](https://ucd-rdavis.github.io/R-DAVIS/labs.html#lab-week-4)<br>[(submit lab 4)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714946) |
| **Week 5 (10/20-22)** | Workshop | [Data Manipulation Pt2](lesson_wk05_data_manipulation_pt2.html)<br>[(submit videos)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714927)<br>[(submit in-class)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714940) | [Lab 5](https://ucd-rdavis.github.io/R-DAVIS/labs.html#lab-week-5)<br>[(submit lab 5)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714947) |
| **Week 6 (10/27-29)** | Workshop | **Midterm** |  |
| **Week 7 (11/3-5)** | Workshop | [Data Visualization I](lesson_wk07_data_visualization.html)<br>[(submit videos)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714926)<br>[(submit in-class)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714941) | [Lab 7](https://ucd-rdavis.github.io/R-DAVIS/labs.html#lab-week-7)<br>[(submit lab 7)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714948) |
| **Week 8 (11/10-12)** | Workshop | [Data Visualization II](lesson_wk08_data_visualization_pt2.html)<br>[(submit videos)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714923)<br>[(submit in-class)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714942) | [Lab 8](https://ucd-rdavis.github.io/R-DAVIS/labs.html#lab-week-8)<br>[(submit lab 8)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714949) |
| **Week 9 (11/17-19)** | Workshop | [Functions](lesson_wk09_functions.html)<br>[(submit videos)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714925)<br>[(submit in-class)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714938) | [Lab 9](https://ucd-rdavis.github.io/R-DAVIS/labs.html#lab-week-9)<br>[(submit lab 9)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714950) |
| **NO CLASS (11/24-26)** | ---- | Thanksgiving Break | ---- |
| **Week 10 (12/1-3)** | Workshop | [Iteration](lesson_wk10_iteration.html)<br>[(submit videos)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714924)<br>[(submit in-class)](https://canvas.ucdavis.edu/courses/1098028/assignments/1714939) | [Lab 10](https://ucd-rdavis.github.io/R-DAVIS/labs.html#lab-week-10)<br>[(submit lab 10)](https://canvas.ucdavis.edu/courses/1098028/assignments/1715201) |
| **Final Exam** | ---- | **TBD** |  |
