---
pagetitle: "Syllabus"
date: '*Updated:* `r format(Sys.time(), "%Y-%b-%d")`'
---

<br>

## Course Description

Computer literacy is now essential in all aspects of science. Data management skills are needed for entering data without errors, storing it in a usable way, and extracting key aspects of the data for analysis. Basic programming is required for everything from accessing and managing data, data visualization, to statistical analysis, and modeling. This course will provide an introduction to data/project management, manipulation, visualization and analysis, across a broad set of ecological data. Class will typically consist of short introductions or question & answer sessions, followed by hands on computing exercises. The course will be taught using git/Github, R/RStudio, and RMarkdown, but the concepts learned will easily apply to all programming languages and database management systems. **No background in databases or R/computational experience is required.**

## Prerequisite Knowledge and Skills

- Willingness to practice coding
- Willingness to try things
- Willingness to fail
- Willingness to put in the time

## Purpose of Course

In this course you will learn fundamental aspects of computer programming that are necessary for conducting ecological research. By the end of the course you will be able to use these tools to import data into R, wrangle various types of data, summarize and analyze data, create visualizations, write reports/manuscripts/CV’s in RMarkdown, save and export data/figures, as well as collaborate on Github with version-controlled projects.  

The focus of this course is to provide graduate students with training that develops and teaches the tools applicable to the entire process of **reproducible data-driven research** and encourage the use of open-source tools. By learning how to get the computer to do your work for you, you will be able to do more science faster, and your future-self will thank you.

## Course Objectives

Students completing this course should be able to:

 - Organize R projects in GitHub
 - Read, import/export data
 - Tidy/summarize and analyze data
 - Create publication-quality graphs and figures
 - Write simple functions/programs in R
 - Search for and access new learning materials to further develop their computational skills
 - Apply these tools to address scientific research questions

## Course Format  

To get the most out of in-class time together, R-DAVIS will combine video material that you watch outside of class with in-person discussion and hands-on activities that we do together in class. Unless unforeseen circumstances arise, videos will be posted by Monday to the relevant week on the Lectures page. Please come to class having watched the material relevant to that week's lesson, completed the video quiz, and perhaps having taken a cursory attempt at trying out what is covered in the videos. We are organizing the course this way so as to spend less of our time together lecturing, and more time working and learning together.

## Grading and Class Expectations 
R-DAVIS is a graded, 3-unit course. The [university's formula](https://registrar.ucdavis.edu/faculty-staff/faculty/courses#:~:text=Academic%20Credit%2C%20Units%2C%20&%20Workload,Committee%20on%20Courses%20of%20Instruction.&text=The%20value%20of%20a%20course,a%20student%2C%20or%20the%20equivalent) for a 3-unit course is that you should expect to spend ~9 hours a week in total on the course. You might spend less time then that, or some weeks you might spend more. Regardless, if you only put in work during the scheduled class time, you are unlikely to meet learning goals for the course.

R-DAVIS grades are based on a combination of several tasks and deliverables. The total number of possible points earned is 250 points. Grades are calculated at points_earned/270

- A = 93-100% | A- = 90-92%
- B+ = 87-89 | B = 83-86 | B- = 80-82%
- C+ = 77-79 | C = 73-76 | C- = 70-72%
- D = 60-69%
- F = < 60%

Points are earned as follows:
- Submitting weekly in-class scratch work. These submissions are credit/no-credit (but we will pay attention to good faith effort) NOTE: WEEKLY IN-CLASS SCRATCH WORK FUNCTIONS AS ATTENDANCE. R-DAVIS only has 10 class sessions (and 10 labs), so missing class means that you are missing a sizable chunk of the course. 10 weeks, 10 points each, out of 90 (i.e., we will drop one (1) absence). The absence can be for any reasons, we do not have "excused" and "unexcused" absences in this course.
- Submitting take-home labs. These submissions are credit/no-credit, but again will be reviewed for good-faith effort (primarily, evidence of working and learning). 9 take-home labs, 10 points each, 90 points total.
- Midterm Exam: In-class exam, 45 points
- Final Exam: In-class (during university-designated examp period), 45 points

We will not take attendance for Tuesday afternoon discussion sections, since not all students are typically there at the same time. But we strongly encourage you to attend. Our experience is that students who engage with R more times during the week have much better learning outcomes. 


## Schedule  

#### Week 1 
*Sept. 23*

- Pre-class setup help

*Sept. 25*

- Course intro

- Intro to git/GitHub and RStudio

#### Week 2 
*Sep. 30*

- Drop-in lab

*Oct. 2*

- Project management

- How R thinks about data
 
#### Week 3 
*Oct. 7*

- Drop-in lab

*Oct. 9*

- Spreadsheet best practices

- Starting with spreadsheets in R

#### Week 4 
*Oct. 14*

- Drop-in lab

*Oct. 16*

- Data manipulation in the tidyverse, part 1

#### Week 5 
*Oct. 21*

- Drop-in lab

*Oct. 23*

- Data manipulation in the tidyverse, part 2

#### Week 6 
*Oct. 28*

- Midterm (during drop-in lab)

*Oct. 30*

- Data visualization, part 1

#### Week 7 
*Nov. 4*

- Drop-in lab

*Nov. 5*

- Data visualization, part 2  

#### Week 8 
*Nov. 11* 

- NO DROP-IN, UNIVERSITY HOLIDAY

*Nov. 13 *

- Date-time data with `lubridate`

- Writing functions

#### Week 9 
*Nov. 18*

- Drop-in lab

*Nov. 20*

- Iteration 

#### Thanksgiving holiday (Nov. 28)   

#### Week 10 
*Dec. 2*

- Drop-in lab

*Dec. 4*

- Collaborative Github Skills

#### Finals 
*Dec. 10*

- Drop-in lab

*Dec. 12*

- Final exam (in-class, normal time period)


