---
title: "Lab Week 3"
format:
  html:
    embed-resources: true
---

This is the Lab Week 3 document for R-DAVIS. Complete the tasks below in this file, then click **Render** and upload the resulting HTML file to Canvas.


Lab this week will be playing with the `surveys` data we worked on in class. Create a new script within your  `scripts` folder called `lastname_week_3_lab.R` (with your own last name). 

Load the `surveys` data frame with the read.csv() function. Create a new data frame called `surveys_base` with only the species_id, the weight, and the plot_type columns. Have this data frame only be the first 5,000 rows. Convert both species_id and plot_type to factors. Remove all rows where there is an NA in the weight column. Explore these variables and try to explain why a factor is different from a character. Why might we want to use factors? Can you think of any examples? 

CHALLENGE:
Create a second data frame called `challenge_base` that only consists of individuals from your `surveys_base` data frame with weights greater than 150g.  



<br>
